test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
digital_ocean:
  service: S3
  endpoint: https://sfo2.digitaloceanspaces.com
  access_key_id: <%= ENV["DIGITAL_OCEAN_ACCESS_KEY"] || Rails.application.credentials.dig(:digital_ocean, :access_key_id) %>
  secret_access_key: <%= ENV["DIGITAL_OCEAN_SECRET_KEY"] || Rails.application.credentials.dig(:digital_ocean, :secret_access_key) %>
  region: sfo2
  bucket: ahoyx

